name: e2e-tests

on: pull_request

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_PRIVATE_KEY: zeyfgzeigfyzegfyuzegf
          envkey_NODE_ENV: "development"
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000,http://51.68.58.83:4000"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: "4000"
          envkey_DB_HOST: localhost
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "postgres"
          envkey_REACT_APP_CITIES_API_KEY: 5HOTkyRP3F+ivysH6OfZSg==LKaQCvFY6GtmLgG5
          envkey_REACT_APP_PHOTOS_API_KEY: U9bVu9v8lwaT6Dd8FblqWfns-f_VAhgubahj0hXRmFc
          directory: server
          file_name: .env
      - name: Run e2e tests
        run: npm run e2e-tests